{"name": "失败的登录", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Test_allure.TestUserLogin object at 0x0000026EA43FC088>\n\n    @allure.title(\"失败的登录\")\n    @allure.step(\"输入用户名\")\n    @allure.step(\"输入密码\")\n    @allure.step(\"提交登录\")\n    def test_user_login_failure(self):\n        # 测试逻辑\n>       assert False\nE       assert False\n\nTest_allure.py:47: AssertionError"}, "steps": [{"name": "输入用户名", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\2_self\\203_Study\\01_GitSpace\\Daily\\daily-python\\24y\\pytest_dir\\TestAllure\\Test_allure.py\", line 47, in test_user_login_failure\n    assert False\n"}, "steps": [{"name": "输入密码", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\2_self\\203_Study\\01_GitSpace\\Daily\\daily-python\\24y\\pytest_dir\\TestAllure\\Test_allure.py\", line 47, in test_user_login_failure\n    assert False\n"}, "steps": [{"name": "提交登录", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"E:\\Downloads\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\2_self\\203_Study\\01_GitSpace\\Daily\\daily-python\\24y\\pytest_dir\\TestAllure\\Test_allure.py\", line 47, in test_user_login_failure\n    assert False\n"}, "start": 1714032218594, "stop": 1714032218594}], "parameters": [{"name": "a", "value": "(<Test_allure.TestUserLogin object at 0x0000026EA43FC088>,)"}], "start": 1714032218594, "stop": 1714032218594}], "parameters": [{"name": "a", "value": "(<Test_allure.TestUserLogin object at 0x0000026EA43FC088>,)"}], "start": 1714032218594, "stop": 1714032218610}], "start": 1714032218594, "stop": 1714032218610, "uuid": "a070f271-06f6-4ae0-942e-c1bc023deb2a", "historyId": "bab0a7a0d499b155d1e11fda635fce44", "fullName": "TestAllure.Test_allure.TestUserLogin#test_user_login_failure", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户管理"}, {"name": "parentSuite", "value": "TestAllure"}, {"name": "suite", "value": "Test_allure"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "JM200601001481"}, {"name": "thread", "value": "212384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestAllure.Test_allure"}]}