{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.feature('test_failure')\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nTest_allure.py:19: AssertionError"}, "description": "this test fails", "start": 1714032218393, "stop": 1714032218393, "uuid": "29733154-18b6-4a86-a6a2-ec78eab7590d", "historyId": "1597d603f2afec8811ea46cca469d799", "fullName": "TestAllure.Test_allure#test_failure", "labels": [{"name": "feature", "value": "test_failure"}, {"name": "parentSuite", "value": "TestAllure"}, {"name": "suite", "value": "Test_allure"}, {"name": "subSuite"}, {"name": "host", "value": "JM200601001481"}, {"name": "thread", "value": "212384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestAllure.Test_allure"}]}